In [1]:
import numpy as np

# Sorgular
## any ve all

In [2]:
np.random.seed(1)

In [3]:
x = np.random.randint(2,18,size=12)
y = np.random.randint(2,18,size=12)

In [4]:
b = x >0 
y = np.all(b)
print(y)

True


In [5]:
b = x < 5 
y = np.any(b)
print(y)

True


## where

In [6]:
x = np.linspace(-4,4,9)
y = np.where(x<0, x**2, x**3)
print(x, y, sep="\n")

[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
[16.  9.  4.  1.  0.  1.  8. 27. 64.]


## select

In [7]:
x = np.linspace(-4,4,9)
y = np.select([x<-1, x<2, x>=2],[x**2,x**3,x**4])
print(x, y, sep="\n")

[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
[ 16.   9.   4.  -1.   0.   1.  16.  81. 256.]


In [8]:
x = np.random.randint(0,100,size=12)
y = np.select([x<30, x<50, x<70, x>= 70],["FF","DD","CC","AA"])
print(x, y, sep="\n")

[11 28 29 14 50 68 87 87 94 96 86 13]
['FF' 'FF' 'FF' 'FF' 'CC' 'CC' 'AA' 'AA' 'AA' 'AA' 'AA' 'FF']


# Tekrarlama düzeltme

## unique

In [9]:
np.random.seed(1)
x = np.random.randint(1,9,size = 12)

In [10]:
y = np.unique(x)

In [11]:
print(x,y,sep="\n")

[6 4 5 1 8 2 4 6 8 1 1 2]
[1 2 4 5 6 8]


## union1d

In [12]:
x = np.array([7,4,9,6])
y = np.array([2,4,6,1])

In [13]:
z = np.union1d(x,y)

In [14]:
print(x, y, z,sep="\n")

[7 4 9 6]
[2 4 6 1]
[1 2 4 6 7 9]


## intersect1d

In [15]:
x = np.array([7,4,9,6])
y = np.array([2,4,6,1])

In [16]:
z = np.intersect1d(x,y)

In [17]:
print(x, y, z,sep="\n")

[7 4 9 6]
[2 4 6 1]
[4 6]


## setdiff1d

In [18]:
x = np.array([7,4,9,6])
y = np.array([2,4,6,1])

In [19]:
z = np.setdiff1d(x,y)

In [20]:
print(x, y, z,sep="\n")

[7 4 9 6]
[2 4 6 1]
[7 9]


In [21]:
z = np.setdiff1d(y,x)

In [22]:
print(x, y, z,sep="\n")

[7 4 9 6]
[2 4 6 1]
[1 2]


## in1d

In [23]:
x = np.array([7,4,9,6])
y = np.array([2,4,6,1])

In [24]:
z = np.in1d(x,y)

In [25]:
print(x, y, z,sep="\n")

[7 4 9 6]
[2 4 6 1]
[False  True False  True]


In [26]:
z = np.in1d(y,x)

In [27]:
print(x, y, z,sep="\n")

[7 4 9 6]
[2 4 6 1]
[False  True  True False]
