# Matrislerde İşlemler

In [1]:
import numpy as np

In [2]:
np.random.seed(1)
x = np.random.randint(low=1, high=100,size=(5,2))
print("Satır = ",x.shape[0])
print("Sutun = ",x.shape[1])
x

Satır =  5
Sutun =  2


array([[38, 13],
       [73, 10],
       [76,  6],
       [80, 65],
       [17,  2]])

In [3]:
for i in range(9):
    print(i)

0
1
2
3
4
5
6
7
8


In [4]:
for i in range(x.shape[0]):
    print(i)

0
1
2
3
4


In [5]:
print(x)

[[38 13]
 [73 10]
 [76  6]
 [80 65]
 [17  2]]


In [6]:
print(*x)

[38 13] [73 10] [76  6] [80 65] [17  2]


In [7]:
for i in range(x.shape[0]):
    print(x)

[[38 13]
 [73 10]
 [76  6]
 [80 65]
 [17  2]]
[[38 13]
 [73 10]
 [76  6]
 [80 65]
 [17  2]]
[[38 13]
 [73 10]
 [76  6]
 [80 65]
 [17  2]]
[[38 13]
 [73 10]
 [76  6]
 [80 65]
 [17  2]]
[[38 13]
 [73 10]
 [76  6]
 [80 65]
 [17  2]]


In [8]:
for i in range(x.shape[0]):
    print(*x)

[38 13] [73 10] [76  6] [80 65] [17  2]
[38 13] [73 10] [76  6] [80 65] [17  2]
[38 13] [73 10] [76  6] [80 65] [17  2]
[38 13] [73 10] [76  6] [80 65] [17  2]
[38 13] [73 10] [76  6] [80 65] [17  2]


In [9]:
for i in range(x.shape[0]):
    print(*x[i])

38 13
73 10
76 6
80 65
17 2


Burda normal olarak değilde tek tek elimizle nasıl ekrana matrisi bastırırız. Hoca onu göstermişti. Konuya başlamadan görelim dedim.

## Matrisin Transpozesi 

In [10]:
print(x)

[[38 13]
 [73 10]
 [76  6]
 [80 65]
 [17  2]]


In [11]:
#Transpozesini ekrana bastıralım ama x değişmez.
print(x.T)

[[38 73 76 80 17]
 [13 10  6 65  2]]


In [12]:
#Veya şu şekildede matrisin transpozesini alabilirsin
print(x.transpose())

[[38 73 76 80 17]
 [13 10  6 65  2]]


In [13]:
x.T.T

array([[38, 13],
       [73, 10],
       [76,  6],
       [80, 65],
       [17,  2]])

In [14]:
x.T.T.reshape(1,10)

array([[38, 13, 73, 10, 76,  6, 80, 65, 17,  2]])

In [ ]:
##Matris

## fliplr
Döndürek yeni oluşturur

In [15]:
print(x)

[[38 13]
 [73 10]
 [76  6]
 [80 65]
 [17  2]]


In [16]:
np.fliplr(x)

array([[13, 38],
       [10, 73],
       [ 6, 76],
       [65, 80],
       [ 2, 17]])

## flipud 

In [17]:
np.flipud(x)

array([[17,  2],
       [80, 65],
       [76,  6],
       [73, 10],
       [38, 13]])

## flip

In [18]:
np.flip(x,axis=0)#fliplr

array([[17,  2],
       [80, 65],
       [76,  6],
       [73, 10],
       [38, 13]])

In [19]:
np.flip(x,axis=1)#flipud

array([[13, 38],
       [10, 73],
       [ 6, 76],
       [65, 80],
       [ 2, 17]])

## rot90

In [22]:
x = np.random.randint(1,9,size=(6,4))
print(x)

[[8 7 1 7]
 [6 2 2 8]
 [8 6 7 2]
 [2 1 5 2]
 [1 1 6 4]
 [8 3 2 1]]


In [24]:
y = np.rot90(x)

In [26]:
print(x,y,sep="\n\n")

[[8 7 1 7]
 [6 2 2 8]
 [8 6 7 2]
 [2 1 5 2]
 [1 1 6 4]
 [8 3 2 1]]

[[7 8 2 2 4 1]
 [1 2 7 5 6 2]
 [7 2 6 1 1 3]
 [8 6 8 2 1 8]]


## hstack ile matrisleri yanyana eklemek

In [ ]:
a = np.array([[1,2],[9,8],[2,4],[1,1]])
b = np.array([[2,3],[4,7],[9,5],[8,8]])

In [ ]:
print(a)

In [ ]:
print(b)

In [ ]:
print(np.hstack((a,b)))#içerisine tuple alıyor.

## vstack ile matrisleri yanyana eklemek

In [ ]:
np.vstack((a,b))

## concatenate
Her ikisini kapsayan bir fonksiyon

In [ ]:
np.concatenate((a,b))

In [ ]:
np.concatenate((a,b),axis=1)

## append

In [ ]:
a

In [ ]:
b

In [ ]:
print(a,"\n")
print(np.append(a,3.2)) #sonuna 4.3 ekledik. Ama tek boyuta dönüşüyor. 

In [ ]:
print(a,"\n")
print(np.append(a,[2,3])) #Dizi ekleyelim. [2,3] sonuna gelicektir. Reshape ile tekrardan matris haline getirebiliriz.

In [ ]:
print(a,"\n")
print(np.append(a,[2,3]).reshape(5,2))#Eski matrisimiz (4,2) lik matristi. Şuan ise (5,2) oldu.

In [ ]:
print(a,"\n")
print(np.append(a,[2,3]).reshape(a.shape[0] + 1 ,2))
#Eski matrisimiz (4,2) lik matristi. 
#Şuan ise (5,2) oldu. a.shape bize matrisin satır sayısını döndürüyor

Benzer şekillerde bir çok örnek yapabiliriz. 

In [ ]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

## insert

In [ ]:
print(a.reshape(1,-1))
print(np.insert(a,2,5))#2. elemana 5 sayısını ekledik.

In [ ]:
print(a.reshape(1,-1))
print(np.insert(a,-1,5))#sondan bir önceki elemana 5 sayısını ekledik.

In [ ]:
print(a.reshape(1,-1))
print(np.insert(a,0,5))#ilk elemana 5 sayısını ekledik.

In [ ]:
print(a.reshape(1,-1))
print(np.insert(arr=a, obj = 2, values = 5))#2. elemana 5 sayısını ekledik.

In [ ]:
print(a.reshape(1,-1))
print(np.insert(arr=a, obj = 2, values = [99,1,2,3,4,99]))#2. elemana 99,1,2,3,4,99 sayısını ekledik.

## delete

In [ ]:
a

In [ ]:
print(a.reshape(1,-1))
print(np.delete(a,0))#0. elemanı 5 sildik.

In [ ]:
print(a.reshape(1,-1))
print(np.delete(a,-1))#sonuncu elemanı sildik

In [ ]:
print(a.reshape(1,-1))
print(np.delete(a,-2))#sondan bir önceki elemanı sildik

In [ ]:
print(a.reshape(1,-1))
print(np.delete(a,-3))#sondan 3. elemanı sildik

In [ ]:
print(a.reshape(1,-1))
print(np.delete(arr=a,obj=-2))#sondan bir önceki elemanı sildik

In [ ]:
print(a,"\n")
print(np.delete(a,1,axis=1))#sondan bir önceki elemanı sildik

In [ ]:
print(a, "\n")
print(np.delete(a,1,axis=0))#ikinci satırı sildik

In [ ]:
print(a, "\n")
print(np.delete(a,obj=0,axis=0))#sondan bir  elemanı sildik

## linalg.matrix_rank
Matrisin rankını bulmamızı sağlar.

In [ ]:
a

In [ ]:
np.linalg.matrix_rank(a)

In [ ]:
print(b)
np.linalg.matrix_rank(b)

In [ ]:
print(x)
np.linalg.matrix_rank(x)

## linalg.det
Determinat almamıza yarar. 

In [ ]:
a = np.round(np.random.uniform(0,1,(3,3))*10,decimals=0)
#Uniform dağılımdan 0,1 arasında 3x3 lük matris oluşturup 10 ile çarptık.
#round ile kırptık gösterilecek kısmını 1.3, 2.1, olmasını sağladık. 
print(a)

In [ ]:
b = np.round(np.random.uniform(0,1,(2,2))*10,decimals=0)
#Uniform dağılımdan 0,1 arasında 3x3 lük matris oluşturup 10 ile çarptık.
#round ile kırptık gösterilecek kısmını 1.3, 2.1, olmasını sağladık. 
print(b)

In [ ]:
np.linalg.det(a)

In [ ]:
np.linalg.det(b)

## linalg.inv
Matrisin tersini almak

In [ ]:
a

In [ ]:
b

In [ ]:
np.linalg.inv(a)

In [ ]:
np.linalg.inv(b)

In [ ]:
bilinencevabiolanmatris = np.array([[2, 0, -1], [0 ,1, 3], [-2, 0, 4]])

In [ ]:
bilinencevabiolanmatris

In [ ]:
np.linalg.inv(bilinencevabiolanmatris) #Mükemmel bir şekilde çalıştığını gördük istersen deneyebilirsin. :D

## Matrisin izini alma 

In [ ]:
a

In [ ]:
a.trace()

In [ ]:
b

In [ ]:
b.trace()

## Numpy matrisin en max-min değerlerini bulma

In [ ]:
a

In [ ]:
a.min()

In [ ]:
a.max()

In [ ]:
b

In [ ]:
b.min()

In [ ]:
b.max()

## Numpy matrisin ortalamasını bulalım

In [ ]:
a

In [ ]:
a.mean()

## Numpy matrisin varyans hesaplama

In [ ]:
a

In [ ]:
a.var()

## Numpy matrisin standart sapma hesaplama;

In [ ]:
a

In [ ]:
a.std()

# NumPy ile Matrislerde Matematiksel İşlemler

## Numpy iki matrisin toplanması;

In [ ]:
a

In [ ]:
b = np.array([[2, 3, 5],[1, 9, 1],[2, 3, 1]])

In [ ]:
b

In [ ]:
np.add(a,b)

In [ ]:
a+b

In [ ]:
x

In [ ]:
a+x #Matrisler eş oması gerekir.

## Numpy iki matrisi çıkarma;

In [ ]:
a

In [ ]:
b

In [ ]:
np.subtract(a,b)

In [ ]:
a-b

In [ ]:
a-x #Matrisler eş oması gerekir.

## Numpy iki matrisi birbiriyle çarpmak;

In [ ]:
a

In [ ]:
b

In [ ]:
np.dot(a,b)

In [ ]:
a@b

In [ ]:
a@x

## NumPy ile Matrislerde Skaler İşlemler

In [ ]:
a

In [ ]:
a * 2

In [ ]:
a * -2

In [ ]:
b * 7 

In [ ]:
a ** 2

In [ ]:
a + 10

In [ ]:
a - 10000

# İki matriste işlemler

In [ ]:
x = np.random.randint(2,18,size=12)
y = np.random.randint(2,18,size=12)

In [ ]:
z = np.add(x,y)
print(x,y,z, sep="\n")

In [ ]:
z = np.subtract(x,y)
print(x,y,z, sep="\n")

In [ ]:
z = np.multiply(x,y)
print(x,y,z, sep="\n")

In [ ]:
z = np.divide(x,y)
print(x,y,z, sep="\n")

In [ ]:
z = np.power(x,y)
print(x,y,z, sep="\n")